export const Constants = {
  rounds: 10,
  httpStatus200: 200,
  httpStatus202: 202,
  httpStatus403: 403,
  httpStatus404: 404,
  invalidPassword: 'Wrong password',
  userAlreadyExists: 'User already exists',
  userDoesNotExists: 'User does not exists',
  userWithThisEmail: 'Email is already used',
  userNotFound: 'User not found',
  userUpdated: 'User updated',
  userNotUpdated: 'User not updated',
  userDeleted: 'User deleted',
  bookAlreadyExists: 'Book already exists',
  bookToUpdateNotTheSame: 'Book to update is not the same',
  bookNotFound: 'Book not found',
  bookUpdated: 'Book updated',
  bookNotUpdated: 'Book not updated',
  bookDeleted: 'Book deleted',
  authorAlreadyExists: 'Author already exists',
  authorWithTheSameName: 'Already exists an author with the same name',
  authorNotFound: 'Author not found',
  authorUpdated: 'Author updated',
  authorNotUpdated: 'Author not updated',
  authorDeleted: 'Author deleted',
};
